# Generated by Django 2.2.5 on 2021-01-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210123_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default=None, max_length=10, null=True),
        ),
    ]
