# Generated by Django 2.2.5 on 2021-01-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210122_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
